CREATE TABLE ACCOUNT
(
    ID         UUID PRIMARY KEY NOT NULL,
    NAME       VARCHAR(255)     NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE BALANCE
(
    ID         UUID PRIMARY KEY NOT NULL,
    ACCOUNT_ID UUID             NOT NULL,
    AMOUNT     DECIMAL(19, 4)   NOT NULL,
    CURRENCY   VARCHAR(3)       NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT(ID)
);

CREATE TABLE TRANSACTION
(
    ID            UUID PRIMARY KEY NOT NULL,
    BALANCE_ID    UUID             NOT NULL,
    AMOUNT        DECIMAL(19, 4)   NOT NULL,
    CURRENCY      VARCHAR(3)       NOT NULL,
    BALANCE_AFTER DECIMAL(19, 4)   NOT NULL,
    TYPE          VARCHAR(255)     NOT NULL,
    UPDATED_AT    TIMESTAMP WITH TIME ZONE NOT NULL,
    CREATED_AT    TIMESTAMP WITH TIME ZONE NOT NULL,
    FOREIGN KEY (BALANCE_ID) REFERENCES BALANCE(ID),
    CONSTRAINT TYPE_CHECK CHECK (TYPE IN ('DEPOSIT', 'WITHDRAWAL'))
);

